dist: trusty
sudo: false
language: node_js
git:
  depth: false
node_js:
  - 15
  - 14
  - 12
  - 10
script:
  - yarn typecheck
  - yarn build
  - ./scripts/test-ci.sh
  - yarn prettier --list-different "{src,tests}/**/*.{js,ts}"
  - yarn lint
  - yarn ruling
after_success:
  - ./scripts/analyze.sh
cache: yarn
notifications:
  email: false
